### ISSUE TITLE
Examples link routes to dead link

### ISSUE THREAD

**Issue by garrettmac** [Bottr-js/Bottr#83] opened 2017-03-16 21:31 UTC
I'd take a look at the examples hyperlink. It's a dead link.

**Comment by jcampbell05** [comment] 2017-03-16 21:36
@garrettmac  seems the server has gone down I'll have a look :)

**Comment by ummahusla** [comment] 2017-04-05 06:52
Closing this, because it's a duplicate of #44.

Currently, all the examples are located in [**Bottr-Examples**](https://github.com/Bottr-js/Bottr-Examples) repository. At some point, we need to migrate it into this repository to `gh-pages` branch.

**Closed as completed by ummahusla** 2017-04-05 06:52 UTC
