### ISSUE TITLE
https://bottr.co/examples page is broken.

### ISSUE THREAD

**Issue by stuartcw** [Bottr-js/Bottr#75] opened 2016-11-14 05:16 UTC
Hi,

I reached [https://bottr.co/examples](https://bottr.co/examples) while checking the documentation on [https://bottr.co](https://bottr.co) but that link seems to be broken.

Regards

**Comment by jcampbell05** [comment] 2016-11-14 10:35
Cheers for this, seems to be something weird with the server we are using - will have this fixed this week.

**Comment by jcampbell05** [comment] 2016-11-14 10:35
Duplicate of #70

**Closed by jcampbell05** 2016-11-14 10:35 UTC
