### ISSUE TITLE
Examples link broken

### ISSUE THREAD

**Issue by albertosantini** [Bottr-js/Bottr#70] opened 2016-10-28 18:49 UTC
Getting `404` clicking on [Examples](https://bottr.co/examples.html) link in the home page.

I saw this commit https://github.com/Bottr-js/Bottr/commit/c692bc8ed8378b9ab59bc8c1e0ca4aaf469c1551, but it is not published to `middleman/build/`.

**Comment by jcampbell05** [comment] 2016-10-28 19:21
@albertosantini Good catch, will fix this straight away.

**Comment by pleabargain** [comment] 2016-12-04 12:03
still broken dec4
https://bottr.co/examples
404

https://goo.gl/photos/3ULoYRFSU2RnDXn16

**Comment by yashmurty** [comment] 2016-12-12 16:41
Still broken. Dec 12.

**Comment by ummahusla** [comment] 2016-12-14 13:33
Closing this, because it's a duplicate of #44.

Currently, all the examples are located in [**Bottr-Examples**](https://github.com/Bottr-js/Bottr-Examples) repository. At some point, we need to migrate it into this repository to `gh-pages` branch.

**Closed by ummahusla** 2016-12-14 13:33 UTC
